name: Python Workflow
on: [push, pull_request]


jobs:
  build:
    name: Build and Run Script
    runs-on: ubuntu-20.04
    env:
        model_url: https://huggingface.co/TheBloke/CodeLlama-7B-Python-GGML/resolve/main/codellama-7b-python.ggmlv3.Q2_K.bin
        output_file: codellama-7b-python.ggmlv3.Q2_K.bin

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, '3.10', 3.11]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Download File
        run: |
          curl -o $RUNNER_TEMP/$output_file -L $model_url

      - name: Run Script
        run: |
            pip3 install -r requirements.txt
            python3 convert-llama-ggml-to-gguf.py --input $RUNNER_TEMP/$output_file --output ./model.gguf
